w3c/machine-learning-workshop

- index.html
fix a couple of other todos at the same time
> Add proposed schedule towards the workshop

- index_zh.html
> add chinese version cfp

- index_zh.html
editorial changes to wording, harmonize space between Chinese and English for better reading experience
> Editorial updates

- index.html
- style.css
Fix [validation errors](https://validator.nu/?doc=https%3A%2F%2Fwww.w3.org%2F2020%2F01%2Fmachine-learning-workshop%2F).
I was also planning to tidy the doc, but maybe it is easier to port these changes over to ja and zh translations this way, and only then tidy?
@dontcallmedom et al help appreciated with translations!
> Make HTML pass validation without errors

- index_ja.html
> for PR #15 in ja

- index_ja.html
@dontcallmedom sorry that I've missed one closing div in my previous PR.
> fix missing deletion of /div

- index.html
- index_ja.html
- index_zh.html
This fixes layout regression introduced by https://github.com/w3c/machine-learning-workshop/commit/05b4ecf8df6e47e2bd25e21eaf8a92165c974892
You poke one thing to fix a layout issue, layout breaks elsewhere 🤔
CSS is amazing.
> Fix header layout

- index_ja.html
> follow 8a727f5

- index.html
- index_ja.html
- speakers.html
- speakers_ja.html
working in place. closes #24
- rebase to master/HEAD
- need to update to HEAD
- un-comment link in English version
> Virtual workshop Japanese version

- index_ja.html
- speakers_ja.html
- fixed wrong og:title (postponed -> online)
- un-commented link to _zh.html
- removed left English text
> fixed wrong links incl. to translations; small fixes

- speakers.html
- style.css
- submit.js
Uses "subject" and "body" header fields per
https://tools.ietf.org/html/rfc6068
Fix #38
> Add Submit a talk proposal form

- speakers_ja.html
> added ja version for PR #39

- presentations.html
Added "how far can we go" - @anssiko you had suggested putting it in the "dev" section, but given the encompassing view the abstract talks about, I'm suggesting here putting it under "opportunities and challenges". Happy to adjust if you disagree
> Add one missing talk

- presentations.html
Proposing to add this in "foundation", next to the discussions of edge/cloud since this propose a slightly different approach to these
> Add proposed talk on collaborative learning

- style.css
Fix an issue of the header text overflowing on narrow screens.
I did not deploy this fix, so I suggest you do a build before merge.
> Make the header more responsive

- talks/captions/nh_webnn.vtt
Thanks for the caption. I fixed some minor things by reviewing my video recording.
Please take a look. Thanks!
> Fix nh_webnn.vtt

- talks/captions/nh_webnn.vtt
The nh_webnn.vtt still has issue. I fixed them again. @dontcallmedom , please take another look. Thanks!
> Remove the unused cue identifier in nh_webnn.vtt

- talks/captions/nh_webnn.vtt
Just reviewed the synchronized slides and video. It looks pretty good with some nits. This PR fixes them. Please take a look, @dontcallmedom . Thanks!
> Tweak nh_webnn.vtt

- speakers.html
From the dept of funny typos: stan**dad**ization :)
> Fix typo in speakers page

- _includes/sponsors.html
> Fix logo inclusion path

- _data/pages.yml
- report_zh.html
Would you like to link the Chinese translation to its original English report? Thank you! @ruoxiran @dontcallmedom
> Chinese translation of the workshop report
